### PR TITLE
fix(ui): improve ui

### LINKED ISSUE #20: [BUG]: fix some UX/UI problems on profile page
### Description of the bug

- "See History" of Quizzes should be the same button as Video one
- Update your profile should not redirect you to another page, just need to show the green feedback tip
- Update profile tip shows "users has been successfully update !", it should be "Your profile has been successfully updated !", french and english.
- On each tab of the profile, when contributor, remove the text 'If you have the necessary rights you can create a video below' since it is useless.

### Steps To Reproduce

Go on profile page, try and see yourself

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JeremyLARDENOIS**
Closes #20 

## 📑 Description

- [X] "See History" of Quizzes should be the same button as Video one
- [X] Update your profile should not redirect you to another page, just need to show the green feedback tip
- [x] Update profile tip shows "users has been successfully update !", it should be "Your profile has been successfully updated !", french and english.
- [x] On each tab of the profile, when contributor, remove the text 'If you have the necessary rights you can create a video below' since it is useless.

### Steps To Reproduce

Go on profile page, try and see yourself

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [X] My code is documented
- [X] I provided unitary tests or procedure to test my code
- [X] My PR have a clear description of what my code is supposed to do

### CODE REVIEW

**Comment by JeremyLARDENOIS** [comment]
I failed my rebase, i will do it later

File: src/modules/users/components/Forms/InformationsForm.component.tsx [hunk 1]
```diff
@@ -62,11 +60,11 @@ export const InformationsForm = ({ user, title }: Props) => {
       const { data: updatedUser } = await updateUser({
         id: user.id,
         body: data,
-      }).unwrap()
+      })
       dispatch(setUser(updatedUser))
 
       // Display the success snackbar
-      snackbarService.notify(CrudAction.UPDATE, Endpoint.Users)
+      snackbarService.createSnackbar('AHAH', { variant: 'success' })
```
Comment (sylvain-reynaud) [inline src/modules/users/components/Forms/InformationsForm.component.tsx:67]: lol

**Review by sylvain-reynaud — APPROVED** [review]
